sh install_brew.sh
sh install_mas.sh
sh install_dock.sh
sh install_hotcorners.sh
sh install_hyperkey.sh
sh install_maccy.sh
sh install_rectangle.sh
sh install_linearmouse.sh
sh install_mos.sh
sh install_cleanup.sh